#!/bin/bash

#  Assume the application is developed using the Java code and the log files generated by the application
#  are stored under the directory /tmp/application/current_date.log. This log file is used when users need
#   to debug any application-level related errors. But due to the increased number of logs in this 
#   location, we want to write a shell script that will delete those logs which were created one month 
#   before.

echo "Deleting log files which are modified within the last 30 days"
PATH=$1
echo "$PATH"
find $PATH -name "*.log" -mtime -30 -delete
#echo "Log files deleted successfully which are modified within the last 30 days"
if [ $? -eq 0 ]; then
    echo "Log files deleted successfully which are modified within the last 30 days"
else
    echo "Failed to delete log files. Please check the path and permissions."
fi